name: Release

on: workflow_dispatch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 🚀 Release
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check permissions
        if: ${{ contains(fromJSON('["mrerberg", "Discipulus101", "Makvagabo"]'), github.actor) == false }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("You don't have permission to run this workflow!");

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn --pure-lockfile

      # - name: Set NPM Token
      #   uses: filipstefansson/set-npm-token-action@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}

      # - name: Up versions
      #   run: npm run packages:version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      # - name: Release
      #   run: npm run pub:ci
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create Release Pull Request or Publish to npm
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          setupGitUser: true
          createGithubReleases: true
          publish: yarn packages:release
          version: yarn packages:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
